# Generated by Django 2.1.7 on 2019-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='c_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='thresh',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
