# Generated by Django 2.1.7 on 2019-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190409_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emb',
            field=models.TextField(max_length=300),
        ),
    ]
