# Generated by Django 2.2.1 on 2019-07-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190713_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_image',
            new_name='upload_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
